Add GitHub Actions workflow

diff --git a/.github/workflows/test2.yaml b/.github/workflows/test2.yaml
--- a/.github/workflows/test2.yaml
+++ b/.github/workflows/test2.yaml
@@ -18,20 +18,28 @@ jobs:
           OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
           TOKEN=$(echo $OIDC_TOKEN | jq -r '.value')
           echo "TOKEN=$TOKEN" >> $GITHUB_ENV
+
       - name: Assume Role with OIDC Token
         id: assume_role
         run: |
           echo "Assuming role with OIDC token..."
-          CREDENTIALS=$(aws sts assume-role-with-web-identity --role-arn arn:aws:iam::766537220951:role/GithubActionsTest --role-session-name GitHubActionsSession --web-identity-token ${{ env.TOKEN }} --duration-seconds 3600)
-          export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')
-          export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')
-          export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')
-          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
+          CREDENTIALS=$(aws sts assume-role-with-web-identity --role-arn arn:aws:iam::766537220951:role/GithubActionsTest --role-session-name GitHubActionsSession --web-identity-token ${{ env.TOKEN }} --duration-seconds 3600 2>&1)
+          if echo "$CREDENTIALS" | jq . > /dev/null 2>&1; then
+            export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')
+            export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')
+            export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')
+            echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
+          else
+            echo "Failed to assume role: $CREDENTIALS"
+            exit 1
+          fi
+
       - name: Pull secret from AWS Secrets Manager
         id: pull_secret
         run: |
           echo "Fetching secret..."
           secret=$(aws secretsmanager get-secret-value --secret-id mySecret --query 'SecretString' --output text)
           echo "secret=$secret" >> $GITHUB_ENV
+
       - name: Use secret
         run: echo "The secret is ${{ env.secret }}"
